% Poorya Aghaomidi
% 9961391001
% Question_11 , main
% Goal : compare AP generated by this model & Figure 20.1 of Matlab For Neuroscientists

clear all; close all; clc;

img = imread('Figure 20.1.jpg');
% Insert Figure 20.1 in 'img' variable 

v = hodgkin_huxley(200, 50);
% Call hodgkin_huxley function to calculate voltage when t = 200 and I_inj = 50

time = [0.01:0.01:200];
% Set the time array when t = 200

figure ;
subplot(2,2,1),plot(time,v),axis([6.5 148 -120 40])
xlabel('Time axis'),ylabel('Membrane Potential');
title('(time voltage) curve when t = 200 and injection current = 50');
% Display time_voltage curve with axis details

subplot(2,2,4),imshow(img)
% Display Figure 20.1

savefig('Comparison figure.fig');
% Save the Comparison figure in current folder